import type { Activity } from "./generated-bindings";

export const activities: Activity[] = [
	{
		id: 1000000,
		parent_id: null,
		activity_type: "project",
		title: "TODO Roadmap",
		description: "Sveltekit + Rust Axum + Cli",
		status: "done",
		url: "",
		is_system: false,
		created_at: "",
		updated_at: "",
	},

	{
		id: 1,
		parent_id: 1000000,
		activity_type: "stage",
		title: "Этап 1: Дизайн и протокол",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 101,
		parent_id: 1,
		activity_type: "task",
		title: "Продумать визуальную структуру виджета",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 1001,
		parent_id: 101,
		activity_type: "sub-task",
		title: "Определить габариты контейнера под оверлей OBS.",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 1002,
		parent_id: 101,
		activity_type: "sub-task",
		title:
			"Выбрать цветовую схему для работы на прозрачном/полупрозрачном фоне.",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 102,
		parent_id: 1,
		activity_type: "task",
		title: "Спроектировать схемы данных",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 1003,
		parent_id: 102,
		activity_type: "sub-task",
		title: "Описать JSON-структуру сущности ToDo (ID, текст, статус).",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 1004,
		parent_id: 102,
		activity_type: "sub-task",
		title:
			"Спроектировать форматы WebSocket-событий (добавление, обновление, удаление).",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},

	{
		id: 2,
		parent_id: 1000000,
		activity_type: "stage",
		title: "Этап 2: Подготовка фронтенда",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 201,
		parent_id: 2,
		activity_type: "task",
		title: "Настроить окружение фронтенд-проекта",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 2001,
		parent_id: 201,
		activity_type: "sub-task",
		title: "Развернуть чистый проект через менеджер пакетов.",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 2002,
		parent_id: 201,
		activity_type: "sub-task",
		title:
			"Интегрировать выбранный CSS-инструмент (фреймворк или препроцессор).",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 202,
		parent_id: 2,
		activity_type: "task",
		title: "Перевести сборщик в режим SPA (Single Page App)",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 2003,
		parent_id: 202,
		activity_type: "sub-task",
		title: "Подключить адаптер для генерации строго статических файлов.",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 2004,
		parent_id: 202,
		activity_type: "sub-task",
		title: "Отключить SSR (серверный рендеринг) в глобальной конфигурации.",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 2005,
		parent_id: 202,
		activity_type: "sub-task",
		title: "Настроить резервный роутинг на index.html (fallback ???).",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 2006,
		parent_id: 202,
		activity_type: "sub-task",
		title: "Настроить сборку в один html файл.",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},

	{
		id: 3,
		parent_id: 1000000,
		activity_type: "stage",
		title: "Этап 3: Статический прототип",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 301,
		parent_id: 3,
		activity_type: "task",
		title: "Создать компоненты интерфейса",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 3001,
		parent_id: 301,
		activity_type: "sub-task",
		title:
			"Написать изолированный компонент для строки подзадачи (текст, галочка).",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 3002,
		parent_id: 301,
		activity_type: "sub-task",
		title:
			"Написать изолированный компонент для строки задачи (текст, галочка, подзадачи).",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 3003,
		parent_id: 301,
		activity_type: "sub-task",
		title: "Написать изолированный компонент для строки этапа (текст, задачи).",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 3004,
		parent_id: 301,
		activity_type: "sub-task",
		title: "Написать главный компонент-контейнер для вывода списка.",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 3005,
		parent_id: 301,
		activity_type: "sub-task",
		title:
			"(Отменен) Добавить базовую анимацию для плавного появления/исчезновения строк.",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 302,
		parent_id: 3,
		activity_type: "task",
		title: "Настроить управление локальным состоянием",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 3006,
		parent_id: 302,
		activity_type: "sub-task",
		title:
			"Создать глобальное реактивное хранилище (state rune) внутри фронтенда.",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 3007,
		parent_id: 302,
		activity_type: "sub-task",
		title:
			"Наполнить состояние статичным массивом задач для немедленной проверки верстки.",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 303,
		parent_id: 3,
		activity_type: "task",
		title: "Проверить отображение в стрим-софте",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 3008,
		parent_id: 303,
		activity_type: "sub-task",
		title: "Скомпилировать проект в финальную статическую папку.",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 3009,
		parent_id: 303,
		activity_type: "sub-task",
		title: "Закинуть сгенерированный index.html в OBS как браузерный источник.",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},

	{
		id: 4,
		parent_id: 1000000,
		activity_type: "stage",
		title: "Этап 4: Разработка бэкенда",
		description: "",
		status: "pending",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 401,
		parent_id: 4,
		activity_type: "task",
		title: "Развернуть архитектуру бэкенда",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 4001,
		parent_id: 401,
		activity_type: "sub-task",
		title:
			"Инициализировать Cargo воркспейс для изоляции сервера и CLI приложения.",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 4002,
		parent_id: 401,
		activity_type: "sub-task",
		title:
			"Создать проект сервера, подключить сетевой фреймворк и асинхронный рантайм.",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 402,
		parent_id: 4,
		activity_type: "task",
		title: "Реализовать постоянное хранение данных",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 4003,
		parent_id: 402,
		activity_type: "sub-task",
		title:
			"Написать модуль для чтения/записи состояния в базу данных sqlite (sqlx миграции).",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 4004,
		parent_id: 402,
		activity_type: "sub-task",
		title:
			"Обеспечить потокобезопасный доступ к данным в памяти сервера (Mutex/RwLock).",
		description: "",
		status: "done",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 403,
		parent_id: 4,
		activity_type: "task",
		title: "Подготовить REST API слой",
		description: "",
		status: "pending",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 4005,
		parent_id: 403,
		activity_type: "sub-task",
		title:
			"Написать обработчик (Handler) для отдачи полного списка задач (GET).",
		description: "",
		status: "pending",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 4006,
		parent_id: 403,
		activity_type: "sub-task",
		title:
			"Написать обработчики для добавления и изменения статуса задач (POST/PATCH).",
		description: "",
		status: "pending",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 4007,
		parent_id: 403,
		activity_type: "sub-task",
		title:
			"Включить и настроить CORS-политику для входящих локальных запросов.",
		description: "",
		status: "pending",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},

	{
		id: 5,
		parent_id: 1000000,
		activity_type: "stage",
		title: "Этап 5: Интеграция SSE",
		description: "",
		status: "pending",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 501,
		parent_id: 5,
		activity_type: "task",
		title: "Организовать SSE-сервер",
		description: "",
		status: "pending",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 502,
		parent_id: 5,
		activity_type: "task",
		title: "Реализовать бродкаст и связать с фронтендом",
		description: "",
		status: "pending",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 5003,
		parent_id: 502,
		activity_type: "sub-task",
		title:
			"Интегрировать отправку сообщений в SSE при каждом успешном вызове REST API.",
		description: "",
		status: "pending",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 5004,
		parent_id: 502,
		activity_type: "sub-task",
		title:
			"Во фронтенде написать функцию начальной загрузки данных через fetch при старте.",
		description: "",
		status: "pending",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 5005,
		parent_id: 502,
		activity_type: "sub-task",
		title:
			"Реализовать постоянное SSE-подключение на фронтенде с логикой переподключения и обработку Lagged.",
		description: "",
		status: "pending",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},

	{
		id: 6,
		parent_id: 1000000,
		activity_type: "stage",
		title: "Этап 6: CLI Утилита и Проверка",
		description: "",
		status: "pending",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 601,
		parent_id: 6,
		activity_type: "task",
		title: "Создать CLI приложение",
		description: "",
		status: "pending",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 6001,
		parent_id: 601,
		activity_type: "sub-task",
		title:
			"Добавить второй бинарник в воркспейс и подключить библиотеку парсинга ввода.",
		description: "",
		status: "pending",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 6002,
		parent_id: 601,
		activity_type: "sub-task",
		title: "Описать дерево команд (widget todo add, widget todo done).",
		description: "",
		status: "pending",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 602,
		parent_id: 6,
		activity_type: "task",
		title: "Настроить отправку команд и сквозной тест",
		description: "",
		status: "pending",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 6003,
		parent_id: 602,
		activity_type: "sub-task",
		title:
			"Внедрить HTTP-клиент в CLI для отправки сформированных JSON-структур на сервер.",
		description: "",
		status: "pending",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
	{
		id: 6004,
		parent_id: 602,
		activity_type: "sub-task",
		title:
			"Провести финальный тест: команда из консоли -> изменение в БД -> сокет -> обновление в OBS.",
		description: "",
		status: "pending",
		url: null,
		is_system: false,
		created_at: "",
		updated_at: "",
	},
];
