// This file has been generated by Specta. Do not edit this file manually.
export type Project = {
	id: number;
	title: string;
	completed: boolean;
	tasks: Task[];
};

export type SubTask = {
	id: number;
	title: string;
	completed: boolean;
	description: string;
};

export type Task = {
	id: number;
	title: string;
	completed: boolean;
	description: string;
	subtasks: SubTask[];
};

export type WsEvent =
	| ({ AddTask: Task } & { DeleteTask?: never; UpdateTask?: never })
	| ({ UpdateTask: Task } & { AddTask?: never; DeleteTask?: never })
	| ({ DeleteTask: number } & { AddTask?: never; UpdateTask?: never });
