// This file has been generated by Specta. Do not edit this file manually.
export type Activity = {
	id: ActivityId;
	parent_id: ActivityId | null;
	activity_type: ActivityType;
	title: string;
	description: string | null;
	status: ActivityStatus;
	url: string | null;
	is_system: boolean;
	created_at: string;
	updated_at: string;
};

export type ActivityId = number;

export type ActivityStatus = "pending" | "in-progress" | "done";

export type ActivityType = "project" | "stage" | "task" | "sub-task";

export type StreamEvent =
	| { variant: "createActivity"; payload: Activity }
	| { variant: "updateActivity"; payload: Activity }
	| { variant: "deleteActivity"; payload: ActivityId };
